# Generated by Django 5.2 on 2025-05-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='who_can_attend',
            new_name='event_type',
        ),
    ]
